PCK_SBD/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^care_point/', include('care_point.urls', namespace='care_point')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

care_point/urls.py
from django.conf.urls import url
from . import views

app_name = 'care_point'

urlpatterns = [

    #index /carepoint
    url(r'^$', views.index, name='index'),

    #OPIEKINOWIE
    url(r'^caregiver/$', views.caregiver, name='caregiver'),
    url(r'^caregiver/add/$', views.caregiver_add, name='caregiver_add'),
    url(r'^caregiver/(?P<caregiver_id>[0-9]+)/$', views.caregiver_details, name='caregiver_details'),
    url(r'^caregiver/(?P<caregiver_id>[0-9]+)/delete/$', views.caregiver_delete, name='caregiver_delete'),
    url(r'^caregiver/(?P<caregiver_id>[0-9]+)/update/$', views.caregiver_update, name='caregiver_update'),

    #CONTRACT
    url(r'^contract/$', views.contract, name='contract'),
    url(r'^contract/add/$', views.contract_add, name='contract_add'),
    url(r'^contract/caregiver/$', views.contract_add_caregiver, name='contract_add_caregiver'),
    url(r'^contract/caregiver/(?P<caregiver_id>[0-9]+)/next$', views.next_contract, name='next_contract'),
    url(r'^contract/caregiver/(?P<caregiver_id>[0-9]+)/$', views.new_worksheet_caregiver, name='new_worksheet_caregiver'),

    url(r'^contract/(?P<contract_id>[0-9]+)/$', views.contract_details, name='contract_details'),
    url(r'^contract/(?P<contract_id>[0-9]+)/delete/$', views.contract_delete, name='contract_delete'),
    url(r'^contract/(?P<contract_id>[0-9]+)/update/$', views.contract_update, name='contract_update'),

    #WARD
    url(r'^ward/$', views.ward, name='ward'),
    url(r'^ward/add/$', views.ward_add, name='ward_add'),
    url(r'^contract/ward/(?P<ward_id>[0-9]+)/$', views.new_worksheet_ward, name='new_worksheet_ward'),
    url(r'^ward/(?P<ward_id>[0-9]+)/$', views.ward_details, name='ward_details'),
    url(r'^ward/(?P<ward_id>[0-9]+)/delete/$', views.ward_delete, name='ward_delete'),
    url(r'^ward/(?P<ward_id>[0-9]+)/update/$', views.ward_update, name='ward_update'),
    #
    # #DECYZJE
    url(r'^decision/$', views.decision, name='decision'),
    url(r'^decision/add/$', views.decision_add, name='decision_add'),
    url(r'^decision/(?P<ward_id>[0-9]+)/ward$', views.next_decision, name='next_decision'),
    url(r'^decision/(?P<decision_id>[0-9]+)/$', views.decision_details, name='decision_details'),
    url(r'^decision/(?P<decision_id>[0-9]+)/delete/$', views.decision_delete, name='decision_delete'),
    url(r'^decision/(?P<decision_id>[0-9]+)/update/$', views.decision_update, name='decision_update'),
    #
    # #ILLNESS
    url(r'^illness/$', views.illness, name='illness'),
    url(r'^illness/add/$', views.illness_add, name='illness_add'),
    url(r'^illness/(?P<illness_id>[0-9]+)/$', views.illness_details, name='illness_details'),
    url(r'^illness/(?P<illness_id>[0-9]+)/delete/$', views.illness_delete, name='illness_delete'),
    url(r'^illness/(?P<illness_id>[0-9]+)/update/$', views.illness_update, name='illness_update'),
    #
    # #ACTIVITY
    url(r'^activity/$', views.activity, name='activity'),
    url(r'^activity/add/$', views.activity_add, name='activity_add'),
    url(r'^activity/(?P<activity_id>[0-9]+)/$', views.activity_details, name='activity_details'),
    url(r'^activity/(?P<activity_id>[0-9]+)/delete/$', views.activity_delete, name='activity_delete'),
    url(r'^activity/(?P<activity_id>[0-9]+)/update/$', views.activity_update, name='activity_update'),
    #
    # #MANAGER
    # url(r'^manager/$', views.manager, name='manager'),
    # url(r'^manager/add/$', views.manager_add, name='manager_add'),
    # url(r'^manager/(?P<manager_id>[0-9]+)/$', views.manager_details, name='manager_details'),
    # url(r'^manager/(?P<manager_id>[0-9]+)/delete/$', views.manager_delete, name='manager_delete'),
    # url(r'^manager/(?P<manager_id>[0-9]+)/update/$', views.manager_update, name='manager_update'),
    #
    # #ADDRESS
    url(r'^address/$', views.address, name='address'),
    url(r'^address/add/$', views.address_add, name='address_add'),
    url(r'^address/(?P<address_id>[0-9]+)/$', views.address_details, name='address_details'),
    url(r'^address/(?P<address_id>[0-9]+)/delete/$', views.address_delete, name='address_delete'),
    url(r'^address/(?P<address_id>[0-9]+)/update/$', views.address_update, name='address_update'),
    #
    # WORKSHEET
    url(r'^worksheet/$', views.worksheet, name='worksheet'),
    url(r'^worksheet/add/$', views.worksheet_add, name='worksheet_add'),
    url(r'^worksheet/(?P<worksheet_id>[0-9]+)/$', views.worksheet_details, name='worksheet_details'),
    url(r'^worksheet/(?P<worksheet_id>[0-9]+)/delete/$', views.worksheet_delete, name='worksheet_delete'),
    url(r'^worksheet/(?P<worksheet_id>[0-9]+)/update/$', views.worksheet_update, name='worksheet_update'),
]

care_point/models.py
from datetime import datetime
from django.db import models


class Point_of_care(models.Model):
    city = models.CharField(max_length=30)

    def __str__(self):
        return self.city


class Manager(models.Model):
    name = models.CharField(max_length=30)
    sname = models.CharField(max_length=30)
    point_of_care = models.ForeignKey(Point_of_care, on_delete=models.CASCADE)

    def __str__(self):
        return '{}, {}, {}'.format(self.name, self.sname, self.point_of_care)


class Caregiver(models.Model):
    name = models.CharField(max_length=30)
    sname = models.CharField(max_length=30)
    point_of_care = models.ForeignKey(Point_of_care, on_delete=models.CASCADE)

    def __str__(self):
        return '{}, {}, {}'.format(self.name, self.sname, self.point_of_care)


class Contract(models.Model):
    CONTRACT_TYPE = (
        ('umowa', 'umowa'),
        ('zlecenie', 'zlecenie')
    )
    genre = models.CharField(max_length=20,
                             choices=CONTRACT_TYPE,
                             default='umowa')
    date_from = models.DateField(default=datetime.now().strftime("%Y-%m-%d"), blank=True, null=True)
    date_to = models.DateField(default=datetime.now().strftime("%Y-%m-%d"), blank=True, null=True)
    caregiver = models.ForeignKey(Caregiver, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return '{}, {}  {}, {}'.format(self.genre, self.date_from, self.date_to, self.caregiver)


class Ward(models.Model):
    name = models.CharField(max_length=30)
    sname = models.CharField(max_length=30)
    pesel = models.CharField(max_length=15)

    def __str__(self):
        return '{}, {}'.format(self.name, self.sname)


class Address(models.Model):
    city = models.CharField(max_length=30)
    street = models.CharField(max_length=30)
    number = models.CharField(max_length=30)
    zip_code = models.CharField(max_length=30)
    ward = models.ForeignKey(Ward, blank=True, null=True)

    def __str__(self):
        return '{}, ul.  {}, {}, kod pocztowy {}'.format(self.city, self.street, self.number, self.zip_code)


class Illness(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=200)

    def __str__(self):
        return '{}, {}'.format(self.name, self.description)


class Activity(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=200)

    def __str__(self):
        return '{}, {}'.format(self.name, self.description)


class Decision(models.Model):
    percent_payment = models.CharField(max_length=5)
    hours = models.CharField(max_length=4)
    charge = models.CharField(max_length=30)
    ward = models.ForeignKey(Ward, blank=True, null=True)
    illness = models.ManyToManyField(Illness, blank=True)
    activity = models.ManyToManyField(Activity, blank=True)

    def __str__(self):
        return 'Doplata w {}%, godziny {}, stawka {}, podopieczny {}'.format(self.percent_payment, self.hours, self.charge, self.ward)


class Worksheet(models.Model):
    CONTRACT_TYPE = (
        ('umowa', 'umowa'),
        ('zlecenie', 'zlecenie')
    )
    genre = models.CharField(max_length=15,
                             choices=CONTRACT_TYPE,
                             default='umowa')
    date = models.DateField(default=datetime.now().strftime("%Y-%m-%d"), blank=True, null=True)
    # date_to = models.DateField(default=datetime.now().strftime("%Y-%m-%d"), blank=True, null=True)
    # working_hours = models.DecimalField(max_digits=5, decimal_places=2)
    hour_from = models.TimeField(default='8:00')
    hour_to = models.TimeField(default='10:00')
    description = models.CharField(max_length=200)
    ward = models.ForeignKey(Ward)
    caregiver = models.ForeignKey(Caregiver)
    decision = models.ForeignKey(Decision, blank=True, null=True)

    def __str__(self):
        return 'opiekun {}, podopieczny {}, date {}, {} - {} '.format(self.caregiver, self.ward, self.date, self.hour_from, self.hour_to)

care_point/forms.py
from django.db.models import TextField

from .models import *
from django import forms


class ContractForm(forms.ModelForm):

    class Meta:
        model = Contract

        fields = ['genre', 'date_from', 'date_to']

        labels = {
            'genre': 'Typ',
            'date_from': 'Data od',
            'date_to': 'Data do',
            # 'caregiver': 'Opiekun',
                }


class Point_of_careForm(forms.ModelForm):

    class Meta:
        model = Point_of_care

        fields = ['city']

        labels = {
            'city': 'miasto',
        }


class ManagerForm(forms.ModelForm):

    class Meta:
        model = Manager

        fields = ['name', 'sname', 'point_of_care']

        labels = {
            'name': 'Imie',
            'sname': 'Nazwisko',
            'point_of_care': 'odzial',
        }


class CaregiverForm(forms.ModelForm):

    class Meta:
        model = Caregiver

        fields = ['name', 'sname', 'point_of_care']

        labels = {
            'name': 'Imie',
            'sname': 'Nazwisko',
            'point_of_care': 'Odzial',
        }



class AddressForm(forms.ModelForm):

    class Meta:
        model = Address

        fields = ['city', 'street', 'number', 'zip_code']

        labels = {
            'city': 'Miasto',
            'street': 'Ulica',
            'number': 'Numer domu',
            'zip_code': 'Kod pocztowy',
        }


class WardForm(forms.ModelForm):

    class Meta:
        model = Ward

        fields = ['name', 'sname', 'pesel']

        labels = {
            'name': 'Imie',
            'sname': 'Nazwisko',
            'pesel': 'PESEL',
            'address': 'Adres',
        }


class DecisionForm(forms.ModelForm):

    illness = forms.ModelMultipleChoiceField(queryset=Illness.objects.all(), widget=forms.CheckboxSelectMultiple())
    activity = forms.ModelMultipleChoiceField(queryset=Activity.objects.all() ,widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Decision

        fields = ['percent_payment', 'hours', 'charge', 'ward', 'illness', 'activity']

        labels = {
            'percent_payment': 'Doplata z MOPS w procentach',
            'hours': 'Przyslugujace godziny',
            'charge': 'Stawka godzinowa',
            'ward': 'Podopieczny',
            'illness': 'Dolegliwosci',
            'activity': 'Czynnosci',
        }


class IllnessForm(forms.ModelForm):

    class Meta:
        model = Illness

        fields = ['name', 'description']

        labels = {
            'name': 'Nazwa shorzenia',
            'description': 'Opis',
        }


class ActivityForm(forms.ModelForm):

    class Meta:
        model = Activity

        fields = ['name', 'description']

        labels = {
            'name': 'Nazwa shorzenia',
            'description': 'Opis',
        }


class WorksheetForm(forms.ModelForm):

    class Meta:
        model = Worksheet

        fields = ['caregiver', 'ward', 'genre', 'decision', 'date', 'hour_from', 'hour_to',
                  'description']

        labels = {
            'caregiver': 'Opiekunka',
            'ward': 'Podopieczny',
            'genre': 'typ zlecenia',
            'decision': 'Decyzji',
            'date': 'Data',
            'hour_from': 'Godzina od',
            'hour_to': 'Godzina do',
        }

care_point/templates/care_point/ward/ward.html
{% extends 'care_point/base.html' %}

{%  block body %}
 {% if ward %}

        <div class="cols-sm-12 col-md-6">
            <div class="container-fluid">
                <table class="table table-hover">
                     <thead>
                        <tr>
                            <th>Podopieczni</th>
                        </tr>
                     </thead>
                     <tbody>
                        {% for w in  ward %}
                                <tr>
                                    <td>
                                        <div class="object_display">
                                            <a href="{% url 'care_point:ward_details' w.id %}"> {{ w.name }} {{ w.sname }}</a>
                                            <a href="{% url 'care_point:ward_update' w.id %}"><button type="button"><span class="glyphicon glyphicon-edit"></span></button></a>
                                            <a href="{% url 'care_point:ward_delete' w.id %}"><button type="button"><span class="glyphicon glyphicon-trash"></span></button></a>
                                        </div>
                                    </td>
                                </tr>
                        {% endfor %}
                     </tbody>
                </table>
            </div>
        </div>


    {% else %}
        <h3>Niema umow do wyswietlenia </h3>
    {% endif %}
{% endblock %}

care_point/templates/care_point/ward/ward_add.html
{% extends 'care_point/base.html' %}

{% block jquery %}
    $("#id_ward").hide();
    $('label[for="id_ward"]').hide()
{% endblock %}

{% block body %}

{% if info %}
    <div class="container">
        <div class="alert alert-danger">
            {{ info }}
        </div>
    </div>
{% endif  %}

<div class="row" >
    <div class="col-md-offset-1 col-sm-10" style="padding: 1%">
        <div class="col-sm-11 col-md-7">
            <div class="panel panel-default">
            <h3 style="padding: 1%">Dane podopiecznego</h3>
                <form class="form-horizontal"  action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                        {% for field in form_ward %}
                            <div class="col-sm-offset-1 col-sm-11">
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <span class="text-danger small">{{ field.errors }}</span>
                                    </div>
                                    <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
                                    <div class="col-sm-10">{{ field }}</div>
                                </div>
                            </div>
                        {% endfor %}
                <h3 style="padding: 1%">Dane adresowe</h3>
                <form class="form-horizontal"  action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                        {% for field in form_address %}
                            <div class="col-sm-offset-1 col-sm-11">
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <span class="text-danger small">{{ field.errors }}</span>
                                    </div>
                                    <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
                                    <div class="col-sm-10">{{ field }}</div>
                                </div>
                            </div>
                        {% endfor %}
                <h3 style="padding: 1%">Decyzja</h3>
                        {% for field in form_decision %}
                            <div class="col-sm-offset-1 col-sm-11">
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <span class="text-danger small">{{ field.errors }}</span>
                                    </div>
                                    <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
                                    <div class="col-sm-10">{{ field }}</div>
                                </div>
                            </div>
                        {% endfor %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                             <button type="submit" class="btn btn-success btn-sm">
                                 <span class="glyphicon glyphicon-plus"></span>Dalej
                             </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

care_point/templates/care_point/ward/ward_details.html
{% extends 'care_point/base.html' %}

{% block body %}

    <div class="col-ms-12 col-md-8">
        <div class="container-fluid">
             <nav class="navbar navbar-default" style="background-color: #CCCCCC">
                <div class="conteiner-fluid" >
                    <div>
                        {% if ward %}
                            <h2 style="padding: 1%">Dane podopiecznego</h2>
                            <div style="padding: 1%">
                                <p style="font-size: large" >{{ ward.name }} {{ ward.sname }}</p>
                            </div>
                        {% else %}
                    <h2>No ward to display</h2>
                         {% endif %}
                    </div>
                </div>
             </nav>
            {% if decision %}
                <div class="col-sm-12 col-md-12">
                    <div class="conteiner-fluid">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Decyzje</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for d in decision %}
                                    <tr>
                                        <td>
                                            <div class="object_display">
                                                <li>
                                                    <a href="{% url 'care_point:decision_details' d.id %}"> {{ d }} </a>
                                                    <a href="{% url 'care_point:decision_update' d.id %}"><button type="button"><span class="glyphicon glyphicon-edit"></span></button></a>
                                                    <a href="{% url 'care_point:decision_delete' d.id %}"><button type="button"><span class="glyphicon glyphicon-trash"></span></button></a>
                                                </li>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            {% else %}
                <div class="row">
                    <h3>Niema decyzji do wyswietlenia </h3>
                </div>
            {% endif %}
           {% if worksheet %}
                <div class="col-sm-12 col-md-12">
                    <div class="conteiner-fluid">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Karty pracy</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for w in worksheet %}
                                    <tr>
                                        <td>
                                            <div class="object_display">
                                                <li>
                                                    <a href="{% url 'care_point:worksheet_details' w.id %}"> {{ w }} </a>
                                                    <a href="{% url 'care_point:worksheet_update' w.id %}"><button type="button"><span class="glyphicon glyphicon-edit"></span></button></a>
                                                    <a href="{% url 'care_point:worksheet_delete' w.id %}"><button type="button"><span class="glyphicon glyphicon-trash"></span></button></a>
                                                </li>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            {% else %}
                <h3>Niema kart pracy do wyswietlenia </h3>
            {% endif %}


             </div>
        </div>
    </div>

    <div class="row">
        <div class="container-fulid">
            {% if ward %}
                 <a href="{% url 'care_point:next_decision' ward.id %}" > <button class="btn btn-primary btn-md">Dodaj decyzje</button> </a>
                 <a href="{% url 'care_point:new_worksheet_ward' ward.id %}" > <button class="btn btn-primary btn-md">Dodaj karte pracy</button> </a>
             {% endif %}
        </div>
    </div>

{% endblock %}

care_point/templates/care_point/ward/ward_update.html
{% extends 'care_point/base.html' %}

{% block body %}

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <form class="form-horizontal"  action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'care_point/form_template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                             <button type="submit" class="btn btn-success btn-sm">
                                 <span class="glyphicon glyphicon-plus"></span>Zapisz
                             </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}