PCK_SBD/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^care_point/', include('care_point.urls', namespace='care_point')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

care_point/urls.py
from django.conf.urls import url
from . import views

app_name = 'care_point'

urlpatterns = [

    #index /carepoint
    url(r'^$', views.index, name='index'),

    #OPIEKINOWIE
    url(r'^caregiver/$', views.caregiver, name='caregiver'),
    url(r'^caregiver/add/$', views.caregiver_add, name='caregiver_add'),
    url(r'^caregiver/(?P<caregiver_id>[0-9]+)/$', views.caregiver_details, name='caregiver_details'),
    url(r'^caregiver/(?P<caregiver_id>[0-9]+)/delete/$', views.caregiver_delete, name='caregiver_delete'),
    url(r'^caregiver/(?P<caregiver_id>[0-9]+)/update/$', views.caregiver_update, name='caregiver_update'),

    #CONTRACT
    url(r'^contract/$', views.contract, name='contract'),
    url(r'^contract/add/$', views.contract_add, name='contract_add'),
    url(r'^contract/caregiver/$', views.contract_add_caregiver, name='contract_add_caregiver'),
    url(r'^contract/caregiver/(?P<caregiver_id>[0-9]+)/next$', views.next_contract, name='next_contract'),
    url(r'^contract/caregiver/(?P<caregiver_id>[0-9]+)/$', views.new_worksheet_caregiver, name='new_worksheet_caregiver'),

    url(r'^contract/(?P<contract_id>[0-9]+)/$', views.contract_details, name='contract_details'),
    url(r'^contract/(?P<contract_id>[0-9]+)/delete/$', views.contract_delete, name='contract_delete'),
    url(r'^contract/(?P<contract_id>[0-9]+)/update/$', views.contract_update, name='contract_update'),

    #WARD
    url(r'^ward/$', views.ward, name='ward'),
    url(r'^ward/add/$', views.ward_add, name='ward_add'),
    url(r'^contract/ward/(?P<ward_id>[0-9]+)/$', views.new_worksheet_ward, name='new_worksheet_ward'),
    url(r'^ward/(?P<ward_id>[0-9]+)/$', views.ward_details, name='ward_details'),
    url(r'^ward/(?P<ward_id>[0-9]+)/delete/$', views.ward_delete, name='ward_delete'),
    url(r'^ward/(?P<ward_id>[0-9]+)/update/$', views.ward_update, name='ward_update'),
    #
    # #DECYZJE
    url(r'^decision/$', views.decision, name='decision'),
    url(r'^decision/add/$', views.decision_add, name='decision_add'),
    url(r'^decision/(?P<ward_id>[0-9]+)/ward$', views.next_decision, name='next_decision'),
    url(r'^decision/(?P<decision_id>[0-9]+)/$', views.decision_details, name='decision_details'),
    url(r'^decision/(?P<decision_id>[0-9]+)/delete/$', views.decision_delete, name='decision_delete'),
    url(r'^decision/(?P<decision_id>[0-9]+)/update/$', views.decision_update, name='decision_update'),
    #
    # #ILLNESS
    url(r'^illness/$', views.illness, name='illness'),
    url(r'^illness/add/$', views.illness_add, name='illness_add'),
    url(r'^illness/(?P<illness_id>[0-9]+)/$', views.illness_details, name='illness_details'),
    url(r'^illness/(?P<illness_id>[0-9]+)/delete/$', views.illness_delete, name='illness_delete'),
    url(r'^illness/(?P<illness_id>[0-9]+)/update/$', views.illness_update, name='illness_update'),
    #
    # #ACTIVITY
    url(r'^activity/$', views.activity, name='activity'),
    url(r'^activity/add/$', views.activity_add, name='activity_add'),
    url(r'^activity/(?P<activity_id>[0-9]+)/$', views.activity_details, name='activity_details'),
    url(r'^activity/(?P<activity_id>[0-9]+)/delete/$', views.activity_delete, name='activity_delete'),
    url(r'^activity/(?P<activity_id>[0-9]+)/update/$', views.activity_update, name='activity_update'),
    #
    # #MANAGER
    # url(r'^manager/$', views.manager, name='manager'),
    # url(r'^manager/add/$', views.manager_add, name='manager_add'),
    # url(r'^manager/(?P<manager_id>[0-9]+)/$', views.manager_details, name='manager_details'),
    # url(r'^manager/(?P<manager_id>[0-9]+)/delete/$', views.manager_delete, name='manager_delete'),
    # url(r'^manager/(?P<manager_id>[0-9]+)/update/$', views.manager_update, name='manager_update'),
    #
    # #ADDRESS
    url(r'^address/$', views.address, name='address'),
    url(r'^address/add/$', views.address_add, name='address_add'),
    url(r'^address/(?P<address_id>[0-9]+)/$', views.address_details, name='address_details'),
    url(r'^address/(?P<address_id>[0-9]+)/delete/$', views.address_delete, name='address_delete'),
    url(r'^address/(?P<address_id>[0-9]+)/update/$', views.address_update, name='address_update'),
    #
    # WORKSHEET
    url(r'^worksheet/$', views.worksheet, name='worksheet'),
    url(r'^worksheet/add/$', views.worksheet_add, name='worksheet_add'),
    url(r'^worksheet/(?P<worksheet_id>[0-9]+)/$', views.worksheet_details, name='worksheet_details'),
    url(r'^worksheet/(?P<worksheet_id>[0-9]+)/delete/$', views.worksheet_delete, name='worksheet_delete'),
    url(r'^worksheet/(?P<worksheet_id>[0-9]+)/update/$', views.worksheet_update, name='worksheet_update'),
]

care_point/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from datetime import datetime as fdt
import datetime as idt
from .forms import *
import itertools


def index(request):
    info = 'info'
    return render(request, 'care_point/index.html', {'info': info})


#CONTRACT
@login_required
def contract(request):
    contracts = Contract.objects.all()
    return render(request, 'care_point/contract/contract.html', {'contracts': contracts})


@login_required
def contract_update(request, contract_id):
    c = get_object_or_404(Contract, pk=contract_id)
    form = ContractForm(data=request.POST or None, instance=c)
    if request.method == 'POST':
        if form.is_valid():
            new = form.save(commit=False)
            new.save()
        return redirect('care_point:contract')
    return render(request, 'care_point/contract/contract_update.html', {'form': form})


@login_required
def contract_details(request, contract_id):
    contract = get_object_or_404(Contract, pk=contract_id)
    return render(request, 'care_point/contract/contract_details.html', {'contract': contract})


@login_required
def contract_delete(request, contract_id):
    contract = get_object_or_404(Contract, pk=contract_id)
    contract.delete()
    return redirect('care_point:contract')


@login_required
def contract_add(request):
    if request.method == 'POST':
        form = ContractForm(data=request.POST)
        if form.is_valid():
            new = form.save(commit=False)
            new.save()
        return redirect('care_point:contract')
    else:
        form = ContractForm()
        return render(request, 'care_point/contract/contract_add.html', {'form': form})


@login_required
def contract_add_caregiver(request):
    if request.method == 'POST':
        form = ContractForm(data=request.POST)
        if form.is_valid():
            new = form.save(commit=False)
            new.save()
            caregiver.contract_set.add(new)
        return redirect('care_point:caregiver')
    else:
        form = ContractForm()
        return render(request, 'care_point/contract/contract_add.html', {'form': form})


@login_required
def next_contract(request, caregiver_id):
    if request.method == 'POST':
        form = ContractForm(data=request.POST)
        if form.is_valid():
            new = form.save(commit=False)
            caregiver = get_object_or_404(Caregiver, pk=caregiver_id)
            new.save()
            caregiver.contract_set.add(new)
        return redirect('care_point:caregiver')
    else:
        form = ContractForm()
        return render(request, 'care_point/contract/contract_add.html', {'form': form})


#CAREGIVER
@login_required
def caregiver(request):
    c = Caregiver.objects.all()
    return render(request, 'care_point/caregiver/caregiver.html', {'caregivers': c})


@login_required
def caregiver_add(request):
    if request.method == 'POST':
        form_caregiver = CaregiverForm(data=request.POST)

        # form_contract.clean_data['data']  : dostep do pola formularza

        form_contract = ContractForm(data=request.POST)

        if form_caregiver.is_valid() and form_contract.is_valid():
            caregiver = form_caregiver.save(commit=False)
            check_caregiver = Caregiver.objects.filter(name=caregiver.name).filter(sname=caregiver.sname).first()
            if check_caregiver != None:
                if caregiver.name == check_caregiver.name and caregiver.sname == check_caregiver.sname:
                    info = "Opiekun o tym imieniu i nazwisku znajduje sie w bazie."
                    form_contract = ContractForm()
                    form_caregiver = CaregiverForm()
                    return render(request, 'care_point/caregiver/caregiver_add.html',
                                  {'form_caregiver': form_caregiver, 'form_contract': form_contract, 'info': info})
            else:
                contract = form_contract.save(commit=False)
                contract.save()
                caregiver.save()
                caregiver.contract_set.add(contract)
        return redirect('care_point:caregiver')
    else:
        form_contract = ContractForm()
        form_caregiver = CaregiverForm()
        # dodawanie wartosci do formularza
        # from = searchTeeamForm({'name': " fc b "})
        return render(request, 'care_point/caregiver/caregiver_add.html',
                      {'form_caregiver': form_caregiver, 'form_contract': form_contract})


@login_required
def caregiver_details(request, caregiver_id):
    caregiver = get_object_or_404(Caregiver, pk=caregiver_id)
    contract = caregiver.contract_set.all()
    worksheet = list(caregiver.worksheet_set.all())
    iterator = 1
    month_now = idt.datetime.now().month
    url_str = "care_point:worksheet_details"

    calendar = '<div class="col-sm-12 col-md-12"><div class="conteiner-fluid">'
    calendar += '<table id="calendar"><tbody>'
    for i in range(0, 5):
        if iterator % 7 == 1:
            calendar += '<tr class="calendar_tr">'
        for j in range(0, 7):
            for w in worksheet:
                if w.date.month == month_now:
                    if w.date.day == iterator:
                        if iterator % 7 == 1:
                            calendar += '<tr class="calendar_tr">'
                        calendar += '<td class="calendar_td">' + iterator.__str__() + '<br>'
                        for w_for_day in worksheet:
                            if w_for_day.date.day == iterator:
                                calendar += '<a href="' + '/care_point/worksheet/'+ w_for_day.id.__str__() + '/'  '"> ' + w_for_day.ward.__str__() +'</a><br>'
                        iterator += 1
                        calendar += '</td>'
                        if iterator % 7 == 1:
                            calendar += '</tr>'
            else:
                if iterator < 32:
                    calendar += '<td class="calendar_td">' +iterator.__str__() + '<br></td>'
                    iterator += 1
            if iterator % 7 == 1:
                calendar += '</tr>'

    calendar += '</tbody></table></div></div>'

    return render(request, 'care_point/caregiver/caregiver_details.html',
                  {'caregiver': caregiver, 'contract': contract, 'worksheet': worksheet, 'calendar': calendar})


@login_required
def caregiver_update(request, caregiver_id):
    c = get_object_or_404(Caregiver, pk=caregiver_id)
    form = CaregiverForm(data=request.POST or None, instance=c)
    if request.method == 'POST':
        if form.is_valid():
            new = form.save(commit=False)
            new.save()
        return redirect('care_point:caregiver')
    return render(request, 'care_point/caregiver/caregiver_update.html', {'form': form})


@login_required
def caregiver_delete(request, caregiver_id):
    caregiver = get_object_or_404(Caregiver, pk=caregiver_id)
    caregiver.delete()
    return redirect('care_point:caregiver')


@login_required
def illness(request):
    illness = Illness.objects.all()
    return render(request, 'care_point/illness/illness.html', {'illness': illness})


@login_required
def illness_add(request):
    if request.method == 'POST':
        form = IllnessForm(data=request.POST)
        if form.is_valid():
            illness = form.save(commit=False)
            illness.save()
        return redirect('care_point:illness')
    else:
        form = IllnessForm()
        return render(request, 'care_point/illness/illness_add.html', {'form': form})


@login_required
def illness_details(request, illness_id):
    illness = get_object_or_404(Illness, pk=illness_id)
    return render(request, 'care_point/illness/illness_details.html', {'illness': illness})


@login_required
def illness_update(request, illness_id):
    i = get_object_or_404(Illness, pk=illness_id)
    form = IllnessForm(data=request.POST or None, instance=i)
    if request.method == 'POST':
        if form.is_valid():
            new = form.save(commit=False)
            new.save()
        return redirect('care_point:illness')
    return render(request, 'care_point/illness/illness_update.html', {'form': form})


@login_required
def illness_delete(request, illness_id):
    illness = get_object_or_404(Illness, pk=illness_id)
    illness.delete()
    return redirect('care_point:illness')


@login_required
def activity(request):
    activity = Activity.objects.all()
    return render(request, 'care_point/activity/activity.html', {'activity': activity})


# ACTIVITY
@login_required
def activity_add(request):
    if request.method == 'POST':
        form = ActivityForm(data=request.POST)
        if form.is_valid():
            activity = form.save(commit=False)
            activity.save()
        return redirect('care_point:activity')
    else:
        form = ActivityForm()
        return render(request, 'care_point/activity/activity_add.html', {'form': form})


@login_required
def activity_details(request, activity_id):
    activity = get_object_or_404(Activity, pk=activity_id)
    return render(request, 'care_point/activity/activity_details.html', {'activity': activity})


@login_required
def activity_update(request, activity_id):

    a = get_object_or_404(Activity, pk=activity_id)
    form = ActivityForm(data=request.POST or None, instance=a)
    if request.method == 'POST':
        if form.is_valid():
            new = form.save(commit=False)
            new.save()
        return redirect('care_point:activity')
    return render(request, 'care_point/activity/activity_update.html', {'form': form})


@login_required
def activity_delete(request, activity_id):
    activity = get_object_or_404(Activity, pk=activity_id)
    activity.delete()
    return redirect('care_point:activity')


#WARD
@login_required
def ward(request):
    ward = Ward.objects.all()
    return render(request, 'care_point/ward/ward.html', {'ward': ward})


@login_required

care_point/templates/care_point/caregiver/caregiver.html
{% extends 'care_point/base.html' %}

{%  block body %}
    {% if caregivers %}
        <div class="col-sm-12 col-md-8">
            <div class="conteiner-fluid">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Opiekunowie</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in caregivers %}
                            <tr>
                                <td>
                                    <div class="object_display">
                                        <li>
                                            <a href="{% url 'care_point:caregiver_details' c.id %}"> {{ c.name }} {{ c.sname }}</a>
                                            <a href="{% url 'care_point:caregiver_update' c.id %}"><button type="button"><span class="glyphicon glyphicon-edit"></span></button></a>
                                            <a href="{% url 'care_point:caregiver_delete' c.id %}"><button type="button"><span class="glyphicon glyphicon-trash"></span></button></a>
                                        </li>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% else %}
        <h3>Niema opiekunow do wyswietlenia </h3>
    {% endif %}
{% endblock %}

care_point/templates/care_point/caregiver/caregiver_add.html
{% extends 'care_point/base.html' %}



{% block body %}

    {% if info %}
        <div class="container">
            <div class="alert alert-danger">
                {{ info }}
            </div>
        </div>
    {% endif  %}
        <div class="row" >
            <div class="col-md-offset-1 col-sm-9" >
                <div class="col-sm-11 col-md-7">
                    <div class="panel panel-default">
                        <form class="form-horizontal"  action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                                {% for field in form_caregiver %}
                                    <div class="col-sm-offset-1 col-sm-8">
                                        <div class="form-group">
                                            <div class="col-sm-offset-2 col-sm-10">
                                                <span class="text-danger small">{{ field.errors }}</span>
                                            </div>
                                            <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
                                            <div class="col-sm-10">{{ field }}</div>
                                        </div>
                                    </div>
                                {% endfor %}
                                {% for field in form_contract %}
                                    <div class="col-sm-offset-1 col-sm-8">
                                        <div class="form-group">
                                            <div class="col-sm-offset-2 col-sm-10">
                                                <span class="text-danger small">{{ field.errors }}</span>
                                            </div>
                                            <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
                                            <div class="col-sm-10">{{ field }}</div>
                                        </div>
                                    </div>
                                {% endfor %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                     <button type="submit" class="btn btn-success btn-sm">
                                         <span class="glyphicon glyphicon-plus"></span>Dalej
                                     </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

care_point/templates/care_point/caregiver/caregiver_details.html
{% extends 'care_point/base.html' %}

{% block body %}
{#{% load mathfilters %}#}

    <div class="col-ms-12 col-md-8">
        <div class="container-fluid, details">
             <nav class="navbar navbar-default, details" style="background-color: #CCCCCC">
                <div class="conteiner-fluid, details" >
                    <div>
                        {% if caregiver %}
                            <h2 style="padding: 1%">Dane opiekuna</h2>
                            <div style="padding: 1%">
                                <p style="font-size: large" >{{ caregiver.name }} {{ caregiver.sname }}</p>
                            </div>
                        {% else %}
                    <h2>No caregiver to display</h2>
                         {% endif %}
                    </div>
                </div>
             </nav>

            {%  if calendar %}
                {{ calendar|safe }}
            {% endif %}

            {% if contract %}
                <div class="col-sm-12 col-md-12">
                    <div class="conteiner-fluid">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Umowy</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for c in contract %}
                                    <tr>
                                        <td>
                                            <div class="object_display">
                                                <li>
                                                    <a href="{% url 'care_point:contract_details' c.id %}"> {{ c }} </a>
                                                    <a href="{% url 'care_point:contract_update' c.id %}"><button type="button"><span class="glyphicon glyphicon-edit"></span></button></a>
                                                    <a href="{% url 'care_point:contract_delete' c.id %}"><button type="button"><span class="glyphicon glyphicon-trash"></span></button></a>
                                                </li>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            {% else %}
                <div class="row">
                    <h3>Niema umow do wyswietlenia </h3>
                </div>
            {% endif %}

            {% if worksheet %}
                <div class="col-sm-12 col-md-12">
                    <div class="conteiner-fluid">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Karty pracy</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for w in worksheet %}
                                    <tr>
                                        <td>
                                            <div class="object_display">
                                                <li>
                                                    <a href="{% url 'care_point:worksheet_details' w.id %}"> {{ w }} </a>
                                                    <a href="{% url 'care_point:worksheet_update' w.id %}"><button type="button"><span class="glyphicon glyphicon-edit"></span></button></a>
                                                    <a href="{% url 'care_point:worksheet_delete' w.id %}"><button type="button"><span class="glyphicon glyphicon-trash"></span></button></a>
                                                </li>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            {% else %}
                <h3>Niema kart pracy do wyswietlenia </h3>
            {% endif %}


             </div>
        </div>
    </div>

    <div class="row">
        <div class="container-fulid">
            {% if caregiver %}
                 <a href="{% url 'care_point:next_contract' caregiver.id %}" > <button class="btn btn-primary btn-md">Przedluz umowe</button> </a>
{#                     TODO ogarnac metode dodawania z carevierem #}
{#                 <a href="{% url 'care_point:worksheet_add' caregiver.id %}" > <button class="btn btn-primary btn-md">Dodaj karte pracy</button> </a>#}
                 <a href="{% url 'care_point:worksheet_add' %}" > <button class="btn btn-primary btn-md">Dodaj karte pracy</button> </a>
             {% endif %}
        </div>
    </div>

{% endblock %}

care_point/templates/care_point/caregiver/caregiver_update.html
{% extends 'care_point/base.html' %}

{% block body %}

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <form class="form-horizontal"  action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'care_point/form_template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                             <button type="submit" class="btn btn-success btn-sm">
                                 <span class="glyphicon glyphicon-plus"></span>Zapisz
                             </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}